version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_HTTP_PORT=8080
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:
